version: '3.9'

services:
  cassandra:
    container_name: cassi
    image: cassandra:latest
    ports:
      - 9042:9042
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=citizix

